### ISSUE TITLE
Lein 2.6.1 plus uberjar aot results in compile error

### ISSUE THREAD

**Issue by cataboom** [weavejester/environ#48] opened 2016-02-16 18:55 UTC
The following combination results in a compile error.

Update to lein 2.6.1.

Create a new lein project and add [environ "1.0.2"] as a dependency.  Also add this config item to project.clj:
  :profiles {:uberjar {:aot :all}}

Then run "lein uberjar".

Result:
Compiling test-lein.core
java.lang.RuntimeException: No dispatch macro for: =, compiling:(core.clj:39:1)
Exception in thread "main" java.lang.RuntimeException: No dispatch macro for: =, compiling:(core.clj:39:1)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$load_one.invoke(core.clj:5692)
	at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
	at clojure.core$load_lib.invokeStatic(core.clj:5736)
	at clojure.core$load_lib.doInvoke(core.clj:5717)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$load_libs.invokeStatic(core.clj:5774)
	at clojure.core$load_libs.doInvoke(core.clj:5758)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:648)
	at clojure.core$require.invokeStatic(core.clj:5796)
	at clojure.core$require.doInvoke(core.clj:5796)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at test_lein.core$loading__5569__auto____36.invoke(core.clj:1)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	at clojure.lang.Compiler.compile1(Compiler.java:7474)
	at clojure.lang.Compiler.compile1(Compiler.java:7464)
	at clojure.lang.Compiler.compile(Compiler.java:7541)
	at clojure.lang.RT.compile(RT.java:406)
	at clojure.lang.RT.load(RT.java:451)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5677.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5697)
	at clojure.core$compile$fn__5682.invoke(core.clj:5903)
	at clojure.core$compile.invokeStatic(core.clj:5903)
	at clojure.core$compile.invoke(core.clj:5895)
	at user$eval20$fn__29.invoke(form-init4296858325558218276.clj:1)
	at user$eval20.invokeStatic(form-init4296858325558218276.clj:1)
	at user$eval20.invoke(form-init4296858325558218276.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No dispatch macro for: =
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:500)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader.read(EdnReader.java:108)
	at clojure.lang.EdnReader.readString(EdnReader.java:64)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	at clojure.edn$read_string.invokeStatic(edn.clj:37)
	at clojure.edn$read_string.invoke(edn.clj:37)
	at environ.core$read_env_file.invokeStatic(core.clj:36)
	at environ.core$read_env_file.invoke(core.clj:33)
	at environ.core$fn__73.invokeStatic(core.clj:42)
	at environ.core$fn__73.invoke(core.clj:39)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	... 62 more
Compilation failed: Subprocess failed

Note that the error goes away if you downgrade to lein 2.6.0 or if you remove the :profiles {:uberjar {:aot :all}} item.

**Comment by weavejester** [comment] 2016-02-16 19:05
Tried the steps to reproduce, but everything works fine for me. It sounds like you have something in a `.lein-env` file that's causing a problem. Can you run `cat .lein-env` and paste the output?

**Comment by cataboom** [comment] 2016-02-16 19:08
I think you nailed it.  Here's the result of cat .lein-env:

#=(clojure.lang.PersistentArrayMap/create {})

I don't remember where that came from.

**Comment by weavejester** [comment] 2016-02-16 19:16
That looks like something that was manually modified, as it doesn't seem like `prn-str` in lein-environ would produce that output. I'm closing this issue as the cause doesn't appear to be directly related to environ.

**Comment by weavejester** [comment] 2016-02-16 19:17
BTW to fix it, just delete your `.lein-env` file, in case that wasn't obvious :)

**Closed by weavejester** 2016-02-16 19:16 UTC

**Comment by cataboom** [comment] 2016-02-16 19:36
Yes, that worked, thanks.  

I’m going to poke around a bit more.  When I first got your note I assumed that I had pulled in some cruft from my production project.  But on reflection I started with a completely blank project to reproduce the problem and somehow that .lein-env file got created.

**Comment by cataboom** [comment] 2016-02-16 19:50
When I add this line to project.clj, it creates the .lein-env file and I get the error:

  :hooks [environ.leiningen.hooks]

I can't remember where I got that from.  I'm guessing the answer is to stop doing it?

**Comment by weavejester** [comment] 2016-02-16 22:04
That's configuration from Environ 0.3.0, but that's no longer required. You should stop doing it now.

**Comment by cataboom** [comment] 2016-02-16 22:06
OK, got it.  Thanks a bunch.
